### ISSUE TITLE
Test fail with current packages

### ISSUE THREAD

**Issue by JGuetschow** [pik-primap/primap2#150]
**Describe the bug**

Test fail after update-venv (all passed before). The

**Failing Test**

make test hat 14 fails. The errors seems to have something to do with the GWP contexts in openscm-units. 

**Expected behavior**

All tests pass

**System (please complete the following information):**

 - OS: Linux mint
 - Python version: 3.8.10 
 - package versions: only a few packages were updated, most of them have nothing to do with the actual code (e.g. sphinx). However, it's not an obvious package like pandas or scmdata-units itself. I add more info here when I have it. 

**Additional context**

Error basically renders primap2 completely unusable so highest priority to fix (or freeze a package version)

**Comment by JGuetschow** [comment]
After going through all updated packages, I think the most likely package to play a role in the error is mypy:
* mypy: 0.990->1.2.0

All other package updates have to do with development, documentation etc.

**Comment by mikapfl** [comment]
Shows how important https://github.com/pik-primap/primap2/issues/130 would be…
