### ISSUE TITLE
read in additional coordinates

### ISSUE THREAD

**Issue by mikapfl** [pik-primap/primap2#25]
At the moment it is not possible to specify [additional coordinates](https://primap2.readthedocs.io/en/stable/data_format_details.html#additional-coordinates) to be read in using the pm2io functions. We should add this functionality.

One problem to solve will be how to represent additional coordinates in the interchange format.

**Comment by JGuetschow** [comment]
Working on it now.

**Comment by JGuetschow** [comment]
implemented in fork: https://github.com/JGuetschow/primap2/tree/read_nir_files
