### ISSUE TITLE
get ready for upcoming pandas 3.0 changes

### ISSUE THREAD

**Issue by mikapfl** [pik-primap/primap2#256]
We should support pandas >= 2.0, and pandas >= 2.0 only. There should be no deprecation warnings when running our tests.

**Comment by JGuetschow** [comment]
I assume you mean support >= 3.0?

**Comment by mikapfl** [comment]
Am I confused? According to https://pandas.pydata.org/docs/whatsnew/index.html , the latest pandas version is 2.2.

**Comment by mikapfl** [comment]
Ah, are you talking about https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#upcoming-changes-in-pandas-3-0 ?

That's probably also worth exploring, to make primap2 ready for pandas 3 as much as possible.

**Comment by JGuetschow** [comment]
Yes, that's what's currently causing all (or most of) the warnings and deprecation notices.
