### ISSUE TITLE
define/store terminology for entity names

### ISSUE THREAD

**Issue by mikapfl** [pik-primap/primap2#26]
**Is your feature request related to a problem? Please describe.**

So far, entities are stored as the data variable names in xarray Datasets, but the terminology is not stored anywhere. Therefore, the terminology is implied and only a single terminology is possible for entities (like in primap1). This could lead to a rather large and confused "primap2_entity" terminology and prevents straight-forward re-use of other terminologies.

**Describe the solution you'd like**

I think we should store the terminology for entity names in a primap2 dataset somewhere. I think there are two obvious places:
1. In the dataset attrs. Then, all variables in a dataset share the same entity terminology. (terminology as *metadata*)
2. In the variable names (in a format like `CO2 (primap2)` and `NY.GDP.MKTP.KD (WB)` or `primap2|CO2` and `WB|NY.GDP.MKTP.KD`). Then, variables from different entity terminologies can be combined in the same dataset. (terminology as *data*)

The two solutions have different compromises:
* readability is arguably better in the common `primap2` case using solution number 1, no juggling of prefixes is necessary.
* including the terminology in the data (solution 2) leads to a lot of repetition.
* overlapping terminologies (whatever, maybe the `primap2` terminology has one definition of `F-gases` and the `FAOstat` terminology has another definition of `F-gases`) can lead to problems when using solution number 1 because it is possible to do calculations e.g. summing two different datasets with differing definitions of `F-gases`, leading to wrong results.

In other places in primap2, we have chosen to include the terminology in the name of the dimension. That way, we don't have to repeat the terminology in each data point. Unfortunately, this solution is not possible for the entity, because there is no name of the entity `dimension` in xarray.

I think I would prefer solution number 1 (terminology as metadata) due to the readability and clear separation of data and metadata. The potential for confusion is acceptable for me because I expect that combining datasets from different sources (and therefore potentially different entity terminologies) is a rather uncommon operation which has to be done with care anyway (dealing with partially overlapping data and discontinuities etc.), so that also checking the entity terminology explicitly is not overly complicated.

**Describe alternatives you've considered**

I considered a few other possibilities:
* Store the terminology in the data variable's attrs. However, this repeats the terminology for every data variable and still doesn't protect from confusion when accidentally combining variables with different terminologies. For me it looks like it combines disadvantages of the two solutions I proposed.
* Mandate a common terminology for all primap2 datasets, enlarge this terminology as needed (the primap1 way of doing things). This is attractive because it will be most straight-forward in a strict primap2 context, however, the primap2 terminology will be sprawling and not very coherent, with ad-hoc added and single-use variable names. Examples for this problem from primap1: `VariousGases` means "CF4, C2F6, C3F8, C4F8, HFC-23, NF3, SF6", `BYEMISS` is poorly defined as "Base year emissions", `VULN` apparently means "vulnerability".

**Implementation**
To implement the change if we go with the "terminology as metadata" solution it is necessary to:
* [x] Change the detailed format description
* [x] Change the validation functions
* [x] Change the read* functions
* [x] Update examples
* [x] Adjust tests

**Comment by mikapfl** [comment]
A refined proposal that Jan and I developed would be to optionally store the terminology in the dataset's attrs (terminology as data). If the attribute is missing from the dataset's attrs, any keys can be used, but if the terminology is given, it has to be adhered to. This would be more flexible and has less tendency to lead to poor definitions like in the primap1 entity terminology because single-use and ad-hoc variable names are possible (without terminology) in less formal contexts (exploratory data analysis etc.), while properly defined entities can be used in more formal contexts (long-term storage, publications, etc.).

**Comment by JGuetschow** [comment]
I think the refined proposal is good. 
* It's good to enable storing of new entities without having to fiddle with existing terminologies (as you said, see PRIMAP1)
* It's important not to have all possible entities in one terminology as it will be a big mess at some point
* Yet you sometimes need special entities, e.g. different forms of GDP. It would be great to be able to use the datasets original terminology without the need to invent new names in the PRIMAP terminology
* Easy combination between terminologies must be possible, or the PRIMAP terminology must contain basic socioeconomic entities (GDP, population, ...)
* For emissions datasets it is still important to transform them to a common methodology to enable easy combination and searching. It's a bit of work, but as emissions datasets are most important in PRIMAP it's good to invest the time.

**Comment by AnnGuenther** [comment]
I also like this approach. I think it is good to have a set of defined "key terminologies" that our operations are based / depend on. And other terminologies that can be chosen more freely. For the latter, some general recommendations could maybe be given, with a set of examples. And maybe a list could be compiled of the ones used so that one can have a look when choosing a new one (might be similar to one that already has been used before, in which case the same terminology could be chosen again). When using non-key terminology, a check should be included for it not to collide with a key-terminology.

**Comment by mikapfl** [comment]
As far as I understand, it would then be good to add a function to `climate_categories` to *combine* two categorizations. At the moment, it is easy to *extend* a categorization, but it would be useful to say "this dataset uses the normal primap2 entity terminology combined with the world bank entity terminology"?

**Comment by JGuetschow** [comment]
What I meant is to combine entities from different terminologies e.g. to get GDP per capita. But combining terminologies is also an interesting idea.

Another point is that we can create mapping tables between categories. Thus we can map datasets into a different terminology. This would e.g. enable mapping of different socio-economical datasets using different terminologies into a standard socio-eco terminology (I use this example because there are tons of ways of defining GDP and it's good to keep them separate as long as possible, but combination / comparison is often necessary).

**Comment by mikapfl** [comment]
Yeah, mappings is a feature that is somewhere on the roadmap, but needs some more thought, I think. Mappings can be quite complex because sometimes there are one-to-one mappings, but others need splitting or more complex stuff.
