### ISSUE TITLE
AR5 CCF GWPs missing

### ISSUE THREAD

**Issue by JGuetschow** [pik-primap/primap2#30]
**Is your feature request related to a problem? Please describe.**

Data using AR5 GWPs witch carbon cycle feedbacks (AR5CCFGWP100) can not be read into primap2

**Describe the solution you'd like**
Integrate AR5 CCF GWPs

**Comment by mikapfl** [comment]
Do you know of a source? Where can we find the relevant conversion factors?

**Comment by AnnGuenther** [comment]
In PRIMAP1 in the SIMCAP_EM_UNITCONVERSION_v3.1.xls (or newer) there is a sheet called AR5CCF, where you can find the GWPs.

**Comment by mikapfl** [comment]
But is there a citable source? in the xls, there is the comment "Assumption - no values provided in IPCC report", sounds suspicious.

**Comment by AnnGuenther** [comment]
On the sheet "Version" this information was added: "For AR5CCF see Supplementary material to Ch 8 of WGI report, Table 8.SM.16". I haven't checked it and do not know who added the GWPs. Johannes might have additional information.

**Comment by AnnGuenther** [comment]
The note "Assumption - no values provided in IPCC report" actually explains the colour-code (orange meaning assumption, with the only orange field being C7F16).

**Comment by mikapfl** [comment]
Aah, thanks for the explanation, I'm not yet trained in reading the PRIMAP xls sheets. (-:

**Comment by mikapfl** [comment]
The source for the AR5GWP100 (no CCF) can be found in https://www.ipcc.ch/site/assets/uploads/2018/02/WG1AR5_Chapter08_FINAL.pdf , Table 8.A.1 (page 731).

The source for the AR5CCFGWP100 can be found in https://www.ipcc.ch/site/assets/uploads/2018/07/WGI_AR5.Chap_.8_SM.pdf , Table 8.SM.16 (page 8SM-24) .

**Comment by JGuetschow** [comment]
Pull request for openscm-units is ready

**Comment by mikapfl** [comment]
We now require a version of openscm-units with AR5CCFGWP100 conversion context.
