### ISSUE TITLE
pyCPA port: readData.read_dataset

### ISSUE THREAD

**Issue by mikapfl** [pik-primap/primap2#5]
Port the functionality of pyCPA's [readData.read_dataset](https://github.com/JGuetschow/pyCPA/blob/master/src/pyCPA/readData/read_data.py#L362).

**Comment by JGuetschow** [comment]
Currently this is configured via yaml files. We have to discuss if we want to keep it that way

**Comment by JGuetschow** [comment]
I think we should wait with this until the datalad functionality is up and running so we can adapt the function accordingly.

**Comment by mikapfl** [comment]
Hm, do we need this at all? As far as I can see, the functionality here is to just read in a yaml file and execute the functions defined in the yaml file with the parameters defined in the yaml file. If we use a python file instead of a yaml file, this can be handled by `import` instead, if needed.

**Comment by JGuetschow** [comment]
I agree that with our current setup we don't need it
